### ISSUE TITLE
Node prerequisite check

### ISSUE THREAD

**Issue by Almerc** [mdaley/lein-kinesis#2]
The executable name for node may differ,depending where it is installed from and which OS, causing the installation prerequisite check to fail. In this case it was on Ubuntu.

More specifically ,due to a package conflict, the executable from Ubuntu repositories is called nodejs instead of node. The checker currently only looks for 'node'.

**Comment by joelittlejohn** [comment]
Only solution I can think of here is to look for `nodejs` (e.g. `which nodejs`) and if that's not found, then use `node` instead.

**Comment by mdaley** [comment]
I tried that on Ubuntu and found some other issues to do with permissions. I'll see if I can work out out a solution when back at work in a few weeks time.

-------- Original Message --------

**Comment by joelittlejohn** [comment]
Any user should be able to run `which nodejs`, no permissions required for this.

**Comment by mdaley** [comment]
I think it was more a problem with the permissions for setting up kinesalite or something else needed.  If you get a chance try on Linux and see if you can get it to work. 

-------- Original Message --------

**Comment by mdaley** [comment]
I think I've solved this issue now.  I've changed the code so that installation of kinesalite is into local context (global context requires sudo on ubuntu) and I've included some instructions to `sudo apt-get install nodejs-legacy` when `nodejs` is installed instead of `node`.  This seems to be the only way to get kinesalite to work as it includes references to `node`.  Read this for more detail: http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

Please try out and tell me if it works....

**Comment by mdaley** [comment]
I've tested this in some service acceptance tests that work on both my mac and on an ubuntu VM so I reckon the problem is solved.  If not, please open a new issue.
